# Generated by Django 2.2.3 on 2019-10-19 03:26

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('Email', models.CharField(max_length=50)),
                ('Destination', multiselectfield.db.fields.MultiSelectField(choices=[('Pluto', 'Pluto'), ('Charon', 'Charon'), ('Nix', 'Nix'), ('Hydra', 'Hydra'), ('Kerberos', 'Kerberos'), ('Styx', 'Styx'), ('Ceres', 'Ceres'), ('MakeMake', 'MakeMake'), ('Haumea', 'Haumea'), ('Hiaka', 'Hiaka'), ('Namaka', 'Namaka'), ('Eris', 'Eris'), ('Dysnomia', 'Dysnomia')], max_length=85)),
                ('Purpose', multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Research', 'Research'), ('Recreation', 'Recreation'), ('Others', 'Others')], max_length=36)),
            ],
        ),
    ]
